### ISSUE TITLE
Errors export in defectDojo

### ISSUE THREAD

**Issue by SinelnikovM** [mpast/mobileAudit#73] opened 2022-12-16 07:53 UTC
Hello.
Deploy mobileAudit version 2.2.1

DefectDojo v. 2.14.2 ( release mode )

DojoConfig:

DEFECTDOJO_URL=http://10.7.27.195:8080/finding/
DEFECTDOJO_API_URL=http://10.7.27.195:8080/api/v2/
DEFECTDOJO_API_KEY=my_token_there_correct_token!
DEFECTDOJO_ENABLED=True

Get Error in logs:

mobileaudit-web-1       | [pid: 13|app: 0|req: 48/68] 192.168.144.4 () {54 vars in 1231 bytes} [Fri Dec 16 07:56:51 2022] GET /finding/create => generated 13038 bytes in 44 msecs (HTTP/1.0 200) 8 headers in 383 bytes (1 switches on core 0)
mobileaudit-nginx-1     | 10.30.164.41 - - [16/Dec/2022:06:56:51 +0000] "GET /finding/create HTTP/1.1" 200 13038 "https://10.30.129.49:1443/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "-"
mobileaudit-web-1       | Fri Dec 16 07:56:58 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /findings/ (ip 192.168.144.4) !!!
mobileaudit-web-1       | Fri Dec 16 07:56:58 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 341] during GET /findings/ (192.168.144.4)
mobileaudit-web-1       | OSError: write error
mobileaudit-web-1       | [pid: 11|app: 0|req: 21/69] 192.168.144.4 () {54 vars in 1221 bytes} [Fri Dec 16 07:56:47 2022] GET /findings/ => generated 2538623 bytes in 10798 msecs (HTTP/1.0 200) 8 headers in 385 bytes (0 switches on core 0)
mobileaudit-web-1       | path component of api base URL http://localhost:8888/api/v1/ is ignored; use FORCE_SCRIPT_NAME instead
mobileaudit-web-1       | [pid: 13|app: 0|req: 49/70] 192.168.144.4 () {52 vars in 1161 bytes} [Fri Dec 16 08:36:30 2022] GET /redoc/ => generated 998 bytes in 11 msecs (HTTP/1.0 200) 8 headers in 240 bytes (1 switches on core 0)

**Comment by mpast** [comment] 2022-12-25 14:33
Hi @SinelnikovM 
Thanks for your report,
Just to confirm, when you create the scan, have you entered an existing defect dojo test id in the form?
<img width="464" alt="image" src="https://user-images.githubusercontent.com/9053588/209472020-2cc4fe21-c70b-4bdd-b0f8-1ac430a5c1d4.png">
Thanks!

**Comment by SinelnikovM** [comment] 2022-12-26 06:31
Hello @mpast 

Yes.

![Uploading image.png…]()
![Uploading image.png…]()

Best regards.

**Comment by mpast** [comment] 2022-12-26 13:19
Hi @SinelnikovM 
I've just merged a PR with a few changes 

To avoid the `path component of api base URL http://localhost:8888/api/v1/ is ignored; use FORCE_SCRIPT_NAME instead`error, I've removed the hardcoded url from the api settings in `app/config/urls.py`

For the broken pipe error, I've not been able to reproduce it so far, but it seems that it could be a timeout from the `wsgi` in the `nginx`, so I've added volumes with the nginx logs. These would be saved into `nginx/logs/access.log` and `nginx/logs/error.log`, and in this last one, in case that error is thrown, it would give us more information and verify if it is a timeout or other thing,
Can you please try to reproduce again with this new version so in case it throws the error again we would have more info in these logs?
Thanks again for all your help!

**Comment by SinelnikovM** [comment] 2022-12-28 16:30
Hello @mpast 

With these changes in the logs, there are no requests for a defectdojo at all.

Logs


[tasks]
  . app.worker.tasks.task_create_scan

[2022-12-28 07:37:06,495: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2022-12-28 07:37:08,499: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2022-12-28 07:37:12,506: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672//
[2022-12-28 07:37:12,510: INFO/MainProcess] mingle: searching for neighbors
[2022-12-28 07:37:13,525: INFO/MainProcess] mingle: all alone
[2022-12-28 07:37:13,594: INFO/MainProcess] celery@050599363bc3 ready.
[2022-12-28 07:38:25,584: INFO/MainProcess] Task app.worker.tasks.task_create_scan[16a7db46-5e71-4e37-a41d-c6f3ddc1a7d6] received
[2022-12-28 07:38:25,644: INFO/ForkPoolWorker-2] Starting analysis on AndroidManifest.xml
[2022-12-28 07:38:25,728: INFO/ForkPoolWorker-2] APK file was successfully validated!
[2022-12-28 07:38:25,729: WARNING/ForkPoolWorker-2] Requested API level 29 is larger than maximum we have, returning API level 28 instead.
INFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 2
[2022-12-28 07:39:15,864: INFO/ForkPoolWorker-2] Task app.worker.tasks.task_create_scan[16a7db46-5e71-4e37-a41d-c6f3ddc1a7d6] succeeded in 50.27860737591982s: None
[2022-12-28 07:59:19,164: INFO/MainProcess] Task app.worker.tasks.task_create_scan[7b1acdad-6ac3-4af2-b7af-90cb696c75b7] received
[2022-12-28 07:59:19,194: INFO/ForkPoolWorker-2] Starting analysis on AndroidManifest.xml
[2022-12-28 07:59:19,256: INFO/ForkPoolWorker-2] APK file was successfully validated!
[2022-12-28 07:59:19,257: WARNING/ForkPoolWorker-2] Requested API level 29 is larger than maximum we have, returning API level 28 instead.
INFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 2
[2022-12-28 08:00:07,677: INFO/ForkPoolWorker-2] Task app.worker.tasks.task_create_scan[7b1acdad-6ac3-4af2-b7af-90cb696c75b7] succeeded in 48.51171727431938s: None

**Comment by mpast** [comment] 2023-01-02 15:10
Hi @SinelnikovM 
I still can't reproduce the issue for now, do you have any error logs in defect dojo?
What is the OS and version of your host machine?
Thanks!

**Closed as completed** 2023-04-12 16:07 UTC
Labels: bug
